# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 2
      docker:
        build: .ide/Dockerfile
        image: node:18-alpine
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al
        - name: run
          script: npm install -g pnpm@latest-10
        - name: install
          script: pnpm install
main:
  push:
    - imports: https://cnb.cool/qingshuPrivate/setting/-/blob/main/envs.yml
    - stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/supbose/mznjs-test.git
            auth_type: https
            username: $GITHUN_USERNAME
            password: $GITHUB_ACCESS_TOKEN
            branch: main
            
