# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 4       
      docker:
        build: .ide/Dockerfile
        image: node:18-alpine
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al
        - name: run
          script: |
            - pnpm install
            
