# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 2
      docker:
        build: .ide/Dockerfile
        image: node:18-alpine
      services:
        - vscode
        - docker
      stages:
        - name: 列出文件
          script: ls -al
        - name: 安装 pnpm
          script: npm install -g pnpm@latest-10
        - name: 安装依赖
          script: pnpm install
main:
  push:
    - imports: https://cnb.cool/qingshuPrivate/setting/-/blob/main/envs.yml
      stages:
        - name: 同步到 GitHub
          image: docker.cnb.cool/mznjs/docker/github-sync
          settings:
            target_url: https://github.com/supbose/mznjs-test.git
            auth_type: https
            username: ${GITHUB_USERNAME}
            password: ${GITHUB_ACCESS_TOKEN}
            git_user: ${GITHUB_USERNAME}
            git_email: ${GITHUB_USERMAIL}
            git_commit: false
            branch: main
