# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 1       
      docker:
        build: .ide/Dockerfile
        image: node:18-alpine
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al
        - name: run
          script: npm install -g pnpm@latest-10
        - name: install
          script: pnpm install --frozen-lockfile
            
