# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 4       
      docker:
        build: .ide/Dockerfile
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al
